#import <UIKit/UIKit.h>
@class VNCClient;
@class VNCView;
@class TerminalSession;
@class LegacyTerminalBuffer;

@interface AppDelegate : NSObject <UIApplicationDelegate, UITextFieldDelegate, UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, UIAlertViewDelegate> {
    UIWindow *_window;
    UIViewController *_controller;
    UIView *_connectionPanel;
    UITextField *_hostField;
    UITextField *_portField;
    UITextField *_passwordField;
    UILabel *_statusLabel;
    UILabel *_speedLabel;
    UISlider *_speedSlider;
    UISegmentedControl *_qualityControl;
    UISegmentedControl *_inputModeControl;
    UIButton *_connectButton;
    UIButton *_profilesButton;
    UIButton *_keyboardButton;
    UIButton *_filesButton;
    UIButton *_settingsButton;
    UIButton *_terminalButton;
    UILabel *_statsLabel;
    UIButton *_toolsButton;
    UIView *_toolsPanel;
    UITextField *_wolMACField;
    UITextField *_broadcastField;
    UITextField *_remoteDisplayField;
    UISwitch *_autoResolutionSwitch;
    UIButton *_matchResolutionButton;
    UILabel *_diagnosticsLabel;
    UISwitch *_precisionSwitch;
    UISwitch *_dragLockSwitch;
    UIButton *_scanLANButton;
    NSMutableArray *_lanResults;
    NSUInteger _reconnectCount;
    UISwitch *_tightSwitch;
    UISwitch *_tlsSwitch;
    UIButton *_fullScreenButton;
    UIButton *_exitFullScreenButton;
    UITextField *_keyboardField;
    UIView *_keyBar;
    VNCView *_vncView;
    VNCClient *_client;
    NSTimer *_reconnectTimer;
    NSTimer *_clipboardTimer;
    NSInteger _lastPasteboardChangeCount;
    BOOL _ctrlArmed;
    BOOL _altArmed;
    BOOL _controlsCollapsed;
    BOOL _fullScreen;
    BOOL _shouldAutoReconnect;
    BOOL _savingProfilePrompt;
    NSMutableArray *_profiles;
    NSInteger _selectedProfileIndex;
    BOOL _profileManageMode;

    UIView *_filesPanel;
    UITextField *_downloadURLField;
    UITableView *_remoteFilesTable;
    UIButton *_browseFilesButton;
    UIButton *_filesUpButton;
    NSMutableArray *_remoteEntries;
    NSURL *_remoteBaseURL;
    NSURLConnection *_browseConnection;
    NSMutableData *_browseData;
    UILabel *_downloadStatusLabel;
    UIProgressView *_downloadProgress;
    UITextView *_fileListView;
    NSURLConnection *_downloadConnection;
    NSFileHandle *_downloadHandle;
    NSString *_downloadPath;
    long long _downloadExpected;
    long long _downloadReceived;

    UIView *_terminalPanel;
    UITextView *_terminalView;
    UITextField *_terminalInput;
    UITextField *_sshUserField;
    UITextField *_sshPortField;
    UITextField *_sshKeyField;
    UISwitch *_sshTunnelSwitch;
    TerminalSession *_terminalSession;
    LegacyTerminalBuffer *_terminalBuffer;
    UIView *_terminalKeyBar;
    TerminalSession *_tunnelSession;
    NSInteger _tunnelLocalPort;

    NSString *_filesToken;
    UITextField *_filesTokenField;
    NSString *_remoteRelativePath;
    NSInteger _selectedRemoteIndex;
    BOOL _uploading;
    BOOL _transferPaused;
    NSMutableArray *_transferQueue;
    NSDictionary *_currentTransfer;
    NSString *_resumeRemotePath;
    long long _downloadResumeOffset;
}
@property (nonatomic, retain) UIWindow *window;
@end
